# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Upload docker

on:
  push:
    branches: [ master ]

env:
  RUN_SERVICE_ACCOUNT_EMAIL: ${{ secrets.RUN_SERVICE_ACCOUNT_EMAIL }}
  RUN_SERVICE_ACCOUNT_KEY: ${{ secrets.RUN_SERVICE_ACCOUNT_KEY }}
  RUN_PROJECT_ID: ${{ secrets.RUN_PROJECT_ID }}
  RUN_REGION: ${{ secrets.RUN_REGION }}
  RUN_SERVICE_NAME: ${{ secrets.RUN_SERVICE_NAME }}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
       version: '286.0.0'
       service_account_email: ${{ env.RUN_SERVICE_ACCOUNT_EMAIL }}
       service_account_key: ${{ env.RUN_SERVICE_ACCOUNT_KEY }}
       project_id: ${{ env.RUN_PROJECT_ID }}

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$RUN_PROJECT_ID/$RUN_SERVICE_NAME:$GITHUB_SHA"

    # Deploy image to Cloud Run
    - name: Deploy
     run: |-
       gcloud run deploy "$SERVICE_NAME" \
         --quiet \
         --region "$RUN_REGION" \
         --image "gcr.io/$RUN_PROJECT_ID/$RUN_SERVICE_NAME:$GITHUB_SHA" \
         --platform "managed" \
         --allow-unauthenticated
